### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.1

### dataset
dataset_dir: data
dataset: skillspan_train
template: llama3
cutoff_len: 2000
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
packing: true

### output
output_dir: saves/Meta-Llama-3-8B-Instruct/lora/sft
logging_steps: 10
save_steps: 2000   
save_total_limit: 3
save_only_model: true
plot_loss: false
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 2.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
max_grad_norm: 0.3
bf16: true
ddp_timeout: 180000000
flash_attn: auto
optim: adamw_torch
weight_decay: 0.0
include_num_input_tokens_seen: true